In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dict1 ={
    "name":["Yash","Vivek","Srinath","Surabhi"],
    "marks":[93,90,88,100],
    "city" :['Mumbai',"Pune","Banglore","Thane"]
}

In [ ]:
df = pd.DataFrame(dict1);

In [ ]:
df.to_csv('friends.csv',index=False)

In [ ]:
frnd = pd.read_csv('friends.csv')
print(frnd)

In [ ]:
# df.head(2)
# df.tail(2)
df.describe()

In [ ]:
frnd['marks']

In [ ]:
series =pd.Series(np.random.rand(10))
type(series)

In [ ]:
newdf = pd.DataFrame(np.random.rand(30,5),index=np.arange(30))
newdf.describe()

In [ ]:
newdf.T 
# get transpose

In [ ]:
newdf.sort_index(axis=1,ascending=False).head()

In [ ]:
#make a copy
newdf2=newdf.copy()
newdf2.columns = list("ABCDE")
print(newdf2.loc[0,'A'])

In [ ]:
#make a column and drop column
newdf2.loc[0,0]=345
newdf2
newdf2.drop(0,axis=1)#drops column

In [ ]:
newdf2.loc[[2,5],['C','D']] #get a view
newdf2.loc[25:, 'A':'C']

In [51]:
newdf2=newdf2.drop(0,axis=1)

In [61]:
newdf2.loc[(newdf2['A']>0.7)&(newdf2['C']<0.5)]
#What is iloc:It doesnt care about indexes and just checks location
newdf2.iloc[7,3]=None
newdf2.dropna(inplace=True)
newdf2

           A         B         C         D         E
0   0.459751  0.621487  0.497949  0.954857  0.021875
1   0.449394  0.895651  0.721032  0.972455  0.293017
2   0.801220  0.322201  0.230770  0.692366  0.681255
3   0.037851  0.024059  0.027055  0.921085  0.853738
4   0.259068  0.670677  0.063959  0.663498  0.273935
5   0.410838  0.046395  0.805834  0.322818  0.752519
6   0.586257  0.002218  0.740087  0.309379  0.686374
9   0.706493  0.626470  0.521677  0.942324  0.261628
10  0.502749  0.396393  0.195659  0.969117  0.497515
11  0.318131  0.510384  0.334130  0.139036  0.999145
12  0.748047  0.365506  0.061423  0.626311  0.394556
13  0.876086  0.544225  0.469537  0.678278  0.626993
14  0.060309  0.230361  0.671388  0.025854  0.274325
15  0.695580  0.457584  0.394383  0.987792  0.369179
16  0.971338  0.238197  0.205648  0.553590  0.117509
17  0.405542  0.059682  0.485849  0.462160  0.907241
18  0.785717  0.505042  0.913764  0.257323  0.105383
19  0.188486  0.326650  0.947911  0.015038  0.793277
20  0.765867  0.655590  0.334206  0.968166  0.103353
21  0.007214  0.500820  0.139578  0.671557  0.788932
22  0.765856  0.670165  0.509003  0.811897  0.630991
23  0.204550  0.509504  0.620044  0.147835  0.636704
24  0.103410  0.872135  0.692091  0.435968  0.701319
25  0.359031  0.429037  0.891239  0.950789  0.694980
26  0.134905  0.976873  0.152720  0.008597  0.293539
27  0.866093  0.871541  0.958180  0.597285  0.510432
28  0.515670  0.016763  0.009202  0.178360  0.793849
29  0.727759  0.100900  0.530682  0.883784  0.896584

In [65]:
newdf2.iloc[1,4]=newdf2.iloc[5,2]
# newdf2.drop_duplicates